name: RSpec

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out branch
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3

    - name: Run rspec
      run: |
        bundle install
        bundle exec rspec spec

    - name: Report coverage
      uses: ggilder/codecoverage@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERAGE_FILE_PATH: coverage/lcov/codecoverage-test-tmp.lcov
        COVERAGE_FORMAT: lcov

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage.lcov
        path: coverage/lcov/codecoverage-test-tmp.lcov
        retention-days: 1
        include-hidden-files: true
